import os
import logging
from supabase import create_client, Client
from supabase.client import ClientOptions

logger = logging.getLogger("RewriteEngine")

# --- DATABASE CONFIG ---
SUPABASE_URL = os.getenv("SUPABASE_URL")
SUPABASE_KEY = os.getenv("SUPABASE_SERVICE_ROLE_KEY")

# Target the 'supabase_functions' schema where your brain data lives
opts = ClientOptions(schema="supabase_functions")
supabase: Client = create_client(SUPABASE_URL, SUPABASE_KEY, options=opts)

def read_file(path: str) -> str:
    """Reads local file content."""
    if not os.path.exists(path): return ""
    with open(path, "r", encoding="utf-8") as f: return f.read()

def write_file(path: str, content: str):
    """Writes content to local file (Ephemeral on Render)."""
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)

def get_rewrite_suggestions():
    """
    Queries Supabase for the latest UNPROCESSED insight generated by the Learning Loop.
    """
    try:
        # Fetch latest summary that hasn't been flagged as PROCESSED
        response = supabase.table("agent_memory")\
            .select("*")\
            .ilike("content", "SUMMARIZED_INSIGHT:%")\
            .not_.ilike("content", "%PROCESSED%")\
            .order("created_at", desc=True)\
            .limit(1)\
            .execute()
        
        memory_rows = response.data or []
        
        if not memory_rows:
            return {"suggestions": [], "count": 0}

        latest_insight = memory_rows[0]["content"].replace("SUMMARIZED_INSIGHT: ", "")
        
        return {
            "suggestions": [f"Apply insight: {latest_insight}"],
            "count": 1,
            "insight_id": memory_rows[0].get("id"),
            "raw_content": latest_insight
        }

    except Exception as e:
        logger.error(f"Error fetching insights: {e}")
        return {"suggestions": [], "count": 0}

def apply_rewrites():
    """
    1. Updates the local agent.md.
    2. Commits the new content to 'system_files' in Supabase (Permanent Storage).
    3. Marks the original insight as PROCESSED to clear the queue.
    """
    data = get_rewrite_suggestions()
    
    if data["count"] > 0:
        insight_id = data.get("insight_id")
        insight_text = data.get("raw_content")
        
        # --- STEP 1: LOAD CURRENT MASTER CONTENT ---
        # We try to pull from Supabase first for persistence; fallback to local disk
        try:
            res = supabase.table("system_files").select("content").eq("file_name", "agent.md").single().execute()
            current_content = res.data["content"]
        except Exception:
            logger.warning("Cloud Master not found, falling back to local agent.md")
            current_content = read_file("agent.md")

        # --- STEP 2: GENERATE UPDATED CONTENT ---
        # In production, an LLM call would merge this intelligently. 
        # Here we append it to the Learned Rules section.
        updated_content = f"{current_content}\n\n## Learned Rule (Auto-Applied)\n- {insight_text}"

        # --- STEP 3: PERSIST CHANGES ---
        try:
            # Update Local Disk (Immediate effect for current session)
            write_file("agent.md", updated_content)

            # Update Cloud Master (Permanent - survives Render restarts)
            supabase.table("system_files").upsert({
                "file_name": "agent.md",
                "content": updated_content
            }).execute()

            # Mark the insight as PROCESSED in the memory logs
            supabase.table("agent_memory")\
                .update({"content": f"PROCESSED_INSIGHT: {insight_text}"})\
                .eq("id", insight_id)\
                .execute()

            return {
                "status": "Success",
                "output": f"Committed insight {insight_id} to Cloud Master and marked as processed."
            }
        except Exception as e:
            logger.error(f"Failed to commit rewrite: {e}")
            return {"status": "Error", "output": str(e)}
    
    return {"status": "Idle", "output": "No new insights found to apply."}
