import os
import logging
from supabase import create_client, Client
from supabase.client import ClientOptions

logger = logging.getLogger("RewriteEngine")

# --- DATABASE CONFIG ---
SUPABASE_URL = os.getenv("SUPABASE_URL")
SUPABASE_KEY = os.getenv("SUPABASE_SERVICE_ROLE_KEY")
opts = ClientOptions(schema="supabase_functions")
supabase: Client = create_client(SUPABASE_URL, SUPABASE_KEY, options=opts)

def read_file(path: str) -> str:
    if not os.path.exists(path): return ""
    with open(path, "r", encoding="utf-8") as f: return f.read()

def write_file(path: str, content: str):
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)

def get_rewrite_suggestions():
    """
    Queries Supabase for the latest summarized insight to generate 
    a dynamic rewrite suggestion instead of a static placeholder.
    """
    agent_text = read_file("agent.md")
    
    try:
        # Fetch the latest summary generated by the Learning Loop
        response = supabase.table("agent_memory")\
            .select("*")\
            .ilike("content", "SUMMARIZED_INSIGHT:%")\
            .order("created_at", desc=True)\
            .limit(1)\
            .execute()
        
        memory_rows = response.data or []
        
        if not memory_rows:
            # Fallback if no learning loop has run yet
            return {
                "suggestions": ["Initial identity refinement needed."], 
                "count": 1 if not agent_text else 0
            }

        # Extract the distilled insight from the content string
        latest_insight = memory_rows[0]["content"].replace("SUMMARIZED_INSIGHT: ", "")
        
        # Create a dynamic suggestion based on the learning material
        suggestions = [f"Refine agent profile based on: {latest_insight}"]
        
        return {
            "suggestions": suggestions,
            "count": len(suggestions),
            "insight_id": memory_rows[0].get("id")
        }

    except Exception as e:
        logger.error(f"Failed to fetch rewrite suggestions: {e}")
        return {"suggestions": ["Error fetching insights"], "count": 0}

def apply_rewrites():
    """
    Simulates applying the rewrite to agent.md.
    In a full implementation, this would involve another LLM call 
    to merge the insight into the .md file.
    """
    data = get_rewrite_suggestions()
    
    if data["count"] > 0:
        # Logic to update the local file would go here
        # For now, we acknowledge the specific insight being applied
        logger.info(f"Applying rewrite: {data['suggestions'][0]}")
        
        return {
            "status": "Success",
            "output": f"Applied {data['count']} rewrites based on the latest learning cycle."
        }
    
    return {"status": "Idle", "output": "Nothing new to rewrite."}
